version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: vr-supermarket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vr_supermarket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Thêm dòng này để Docker tự chạy file .sql khi khởi tạo lần đầu
      - ./app/db/001_create_auth_tables.sql:/docker-entrypoint-initdb.d/001_create_auth_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
